import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const sb=createClient('https://ethrejmgwrizrsxqwjhz.supabase.co','sb_publishable__Hgq_ISX-QkhPb2oGSJoCQ_GBjCbOOk');const $=s=>document.querySelector(s);let profile=null,selected=null,editing=null;
const msg=x=>alert(x.message||x);async function boot(){const{data:{session}}=await sb.auth.getSession();if(!session)return showAuth();const{data,error}=await sb.from('profiles').select('*').eq('id',session.user.id).single();if(error)return msg(error);profile=data;if(!profile.active||profile.role==='pending'){await sb.auth.signOut();showAuth();return msg('帳號尚未獲最高管理者核准')}$('#auth').hidden=true;$('#app').hidden=false;$('#account').textContent=`${profile.email} · ${profile.role==='super_admin'?'最高管理者':'子管理者'}`;$('#users').hidden=profile.role!=='super_admin';loadPatients()}
function showAuth(){$('#auth').hidden=false;$('#app').hidden=true}
$('#authForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),{error}=await sb.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)return $('#authMsg').textContent=error.message;boot()};
$('#signup').onclick=async()=>{const f=new FormData($('#authForm')),{error}=await sb.auth.signUp({email:f.get('email'),password:f.get('password')});$('#authMsg').textContent=error?error.message:'申請完成；請先驗證電子郵件，再等待最高管理者核准。'};
$('#logout').onclick=async()=>{await sb.auth.signOut();location.reload()};$('#search').oninput=()=>loadPatients();
async function loadPatients(){let q=$('#search').value.trim(),query=sb.from('patients').select('*,records(id,visit_date,body_part,treatment,notes)').order('created_at',{ascending:false});const{data,error}=await query;if(error)return msg(error);const rows=(data||[]).filter(p=>!q||JSON.stringify(p).includes(q));$('#patientList').innerHTML=rows.map(p=>`<button class="patient" data-id="${p.id}"><b>${esc(p.name)}</b><small>${p.records.length} 筆紀錄</small></button>`).join('');document.querySelectorAll('.patient').forEach(b=>b.onclick=()=>openPatient(b.dataset.id))}
async function openPatient(id){const{data,error}=await sb.from('patients').select('*,records(*)').eq('id',id).single();if(error)return msg(error);selected=data;selected.records.sort((a,b)=>b.visit_date.localeCompare(a.visit_date));$('#detail').innerHTML=`<div class="detailHead"><div><small>病人</small><h2>${esc(data.name)}</h2></div><div><button class="danger" id="delPatient">刪除病人</button><button id="addRecord">＋新增紀錄</button></div></div><div class="records">${data.records.map(r=>`<article class="card"><span class="pill">${esc(r.body_part)}</span> ${r.visit_date}<p><b>處理方式：</b>${esc(r.treatment)}</p>${r.notes?`<p><b>備註：</b>${esc(r.notes)}</p>`:''}<footer><button class="edit" data-id="${r.id}">修改</button><button class="danger del" data-id="${r.id}">刪除</button></footer></article>`).join('')||'<div class="welcome">尚無紀錄</div>'}</div>`;$('#addRecord').onclick=()=>recordModal();$('#delPatient').onclick=deletePatient;document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>recordModal(data.records.find(r=>r.id===b.dataset.id)));document.querySelectorAll('.del').forEach(b=>b.onclick=()=>deleteRecord(b.dataset.id))}
$('#addPatient').onclick=()=>openModal('新增病人','<label>姓名<input name="name" required></label>',async f=>sb.from('patients').insert({name:f.get('name')}));
function recordModal(r=null){editing=r;openModal(r?'修改紀錄':'新增紀錄',`<label>日期<input name="visit_date" type="date" value="${r?.visit_date||new Date().toLocaleDateString('sv-SE')}" required></label><label>受傷／處理部位<input name="body_part" value="${esc(r?.body_part||'')}" required></label><label>處理方式<input name="treatment" value="${esc(r?.treatment||'')}" required></label><label>備註<textarea name="notes">${esc(r?.notes||'')}</textarea></label>`,async f=>{const v=Object.fromEntries(f);return r?sb.from('records').update(v).eq('id',r.id):sb.from('records').insert({...v,patient_id:selected.id})})}
function openModal(title,fields,save){$('#modalTitle').textContent=title;$('#modalFields').innerHTML=fields;$('#modal').showModal();$('#modalForm').onsubmit=async e=>{e.preventDefault();const{error}=await save(new FormData(e.target));if(error)return msg(error);$('#modal').close();await loadPatients();if(selected)await openPatient(selected.id)}}$('#cancel').onclick=()=>$('#modal').close();
async function deleteRecord(id){if(!confirm('確定刪除此紀錄？'))return;const{error}=await sb.from('records').delete().eq('id',id);if(error)return msg(error);openPatient(selected.id)}async function deletePatient(){const n=prompt(`請輸入「${selected.name}」確認刪除病人及全部紀錄`);if(n!==selected.name)return;const{error}=await sb.from('patients').delete().eq('id',selected.id);if(error)return msg(error);selected=null;$('#detail').innerHTML='<div class="welcome">病人已刪除</div>';loadPatients()}
$('#backup').onclick=async()=>{const[p,r]=await Promise.all([sb.from('patients').select('*'),sb.from('records').select('*')]);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({patients:p.data,records:r.data,exported_at:new Date().toISOString()},null,2)],{type:'application/json'}));a.download=`medical-backup-${new Date().toLocaleDateString('sv-SE')}.json`;a.click()};
$('#users').onclick=async()=>{const{data}=await sb.from('profiles').select('*').order('created_at');openModal('帳號管理',(data||[]).map(u=>`<div class="userrow"><span>${esc(u.email)}<small>${u.role}</small></span>${u.role!=='super_admin'?`<button type="button" data-user="${u.id}" data-active="${!u.active}">${u.active?'停用':'核准'}</button>`:''}</div>`).join(''),async()=>({}));document.querySelectorAll('[data-user]').forEach(b=>b.onclick=async()=>{await sb.from('profiles').update({active:b.dataset.active==='true',role:b.dataset.active==='true'?'sub_admin':'pending'}).eq('id',b.dataset.user);$('#modal').close();$('#users').click()})};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let idle;['click','keydown','touchstart'].forEach(e=>addEventListener(e,()=>{clearTimeout(idle);idle=setTimeout(()=>$('#logout').click(),15*60*1000)}));boot();
