import{sb}from'./supabase.js?v=8';const $=s=>document.querySelector(s);let profile,categories=[],patients=[],bodyOptions=[],bodyDetails=[],treatmentOptions=[],active='all';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const can=p=>profile?.role==='super_admin'||profile?.permissions?.[p]===true||(p.endsWith('_treatment')&&profile?.permissions?.manage_treatments===true);
const audit=(action,type=null,id=null,description=null)=>sb.rpc('write_audit',{p_action:action,p_entity_type:type,p_entity_id:id,p_description:description});
async function boot(){const{data:{session}}=await sb.auth.getSession();if(!session)return;const{data:p}=await sb.from('profiles').select('*').eq('id',session.user.id).single();if(!p?.active){await sb.auth.signOut();$('#authMsg').textContent='此帳號已停用';return}profile=p;$('#auth').hidden=true;$('#app').hidden=false;$('#users').hidden=p.role!=='super_admin';$('#importJson').hidden=p.role!=='super_admin';$('#backup').hidden=p.role!=='super_admin'&&!can('export_data');$('#bodyPartManage').hidden=!can('manage_body_parts');$('#treatmentManage').hidden=!Object.keys(p.permissions||{}).some(k=>k.includes('treatment')&&can(k));$('#categoryManage').hidden=!can('manage_categories');await sb.rpc('mark_current_login');await audit('登入成功','profile',p.id);if(p.must_change_password)return forcePasswordChange();await load()}
$('#showPassword').onclick=()=>{const x=$('#loginPassword'),show=x.type==='password';x.type=show?'text':'password';$('#showPassword').textContent=show?'隱藏密碼':'顯示密碼'};
$('#authForm').onsubmit=async e=>{e.preventDefault();$('#authMsg').textContent='登入中…';const f=new FormData(e.target),{error}=await sb.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)return $('#authMsg').textContent='帳號或密碼錯誤';boot()};$('#logout').onclick=async()=>{await audit('登出','profile',profile?.id);await sb.auth.signOut();history.replaceState(null,'',location.pathname);location.reload()};
function forcePasswordChange(){form('首次登入修改密碼',`<p>請先設定新密碼才能使用系統。</p><label class="field">新密碼<input name="password" type="password" minlength="8" required></label><label class="field">確認新密碼<input name="confirm" type="password" minlength="8" required></label>`,async f=>{const pw=String(f.get('password'));if(pw!==f.get('confirm'))return{error:{message:'兩次密碼不一致'}};if(!/^(?=.*[A-Za-z])(?=.*\d).{8,}$/.test(pw))return{error:{message:'密碼至少 8 字元，且需包含英文字母與數字'}};const x=await sb.auth.updateUser({password:pw});if(x.error)return x;await sb.rpc('complete_password_change');await audit('修改首次登入密碼','profile',profile.id);setTimeout(()=>location.reload(),300);return x},'儲存新密碼')}
async function load(){const[c,p,b,d,t]=await Promise.all([sb.from('categories').select('*').order('sort_order'),sb.from('patients').select('*,records(*,record_body_parts(*,record_body_part_details(*)),record_treatments(*))').order('created_at'),sb.from('body_part_options').select('*').order('sort_order'),sb.from('body_part_detail_options').select('*').order('sort_order'),sb.from('treatment_options').select('*').order('sort_order')]);if(c.error)return alert('請先執行資料庫 migration');if(b.error)return alert('請先執行 02-structured-options-v3.sql');categories=c.data||[];patients=p.data||[];bodyOptions=b.data||[];bodyDetails=d.data||[];treatmentOptions=t.data||[];renderSide();renderFolders()}
function renderSide(){$('#allCount').textContent=patients.length;$('#categoryList').innerHTML=categories.map(c=>`<button class="sideItem ${active===c.id?'active':''}" data-cat="${c.id}">📁 ${esc(c.name)} <span>${patients.filter(p=>p.category_id===c.id).length}</span></button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{active=b.dataset.cat;renderSide();renderFolders()})}
function renderFolders(){let list=active==='all'?patients:patients.filter(p=>p.category_id===active),q=$('#globalSearch').value.trim().toLowerCase();if(q)list=list.filter(p=>{const cat=categories.find(c=>c.id===p.category_id)?.name||'';return`${p.name} ${cat} ${JSON.stringify(p.records)}`.toLowerCase().includes(q)});const sort=$('#sort').value;list.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'zh-Hant'):sort==='count'?(b.records?.length||0)-(a.records?.length||0):sort==='created'?new Date(b.created_at)-new Date(a.created_at):new Date(b.updated_at||b.created_at)-new Date(a.updated_at||a.created_at));$('#pageTitle').textContent=q?'搜尋結果':active==='all'?'所有個案':categories.find(c=>c.id===active)?.name||'個案';$('#workspace').innerHTML=`<div class="folderGrid">${list.map(p=>{const cat=categories.find(c=>c.id===p.category_id)?.name||'未分類',dates=q?(p.records||[]).filter(r=>`${r.visit_date} ${r.body_part} ${r.treatment} ${r.notes}`.toLowerCase().includes(q)).map(r=>r.visit_date.replaceAll('-','/')).slice(0,5):[];return`<button class="folder" data-patient="${p.id}"><span class="folderIcon">📁</span><b>${esc(p.name)}</b><small>所屬分類：${esc(cat)}</small><small>${esc(p.patient_code||'')} · ${p.records?.length||0} 筆紀錄</small>${dates.length?`<small>符合紀錄：${dates.join('、')}</small>`:`<small>更新 ${new Date(p.updated_at||p.created_at).toLocaleDateString('zh-TW')}</small>`}</button>`}).join('')}</div>`;document.querySelectorAll('[data-patient]').forEach(b=>b.onclick=()=>openPatient(b.dataset.patient))}
function openPatient(id){const p=patients.find(x=>x.id===id),cat=categories.find(c=>c.id===p.category_id);$('#pageTitle').textContent=p.name;$('#workspace').innerHTML=`<div class="breadcrumb"><button id="back">‹ ${esc(cat?.name||'未分類')}</button></div><div class="caseHead"><div><h2>📁 ${esc(p.name)}</h2><div class="caseMeta">${esc(cat?.name||'未分類')} · 建立 ${new Date(p.created_at).toLocaleDateString('zh-TW')} · ${p.records.length} 筆</div></div><div><button id="deletePatient">刪除個案</button><button id="editPatient">編輯個案</button><button id="movePatient">移動分類</button><button class="primary" id="addRecord">＋ 新增紀錄</button></div></div>${[...p.records].sort((a,b)=>b.visit_date.localeCompare(a.visit_date)).map(r=>`<details class="recordFile"><summary>📄 ${r.visit_date.replaceAll('-','/')}</summary><div class="recordBody"><p><b>部位：</b>${esc(r.body_part)}</p><p><b>處理：</b>${esc(r.treatment)}</p><p><b>備註：</b>${esc(r.notes)}</p><div class="recordActions"><button data-edit="${r.id}">編輯</button><button data-copy="${r.id}">複製</button><button data-delete="${r.id}">刪除</button></div></div></details>`).join('')}`;$('#back').onclick=renderFolders;$('#deletePatient').onclick=()=>deletePatient(p);$('#editPatient').onclick=()=>editPatient(p);$('#movePatient').onclick=()=>movePatient(p);$('#addRecord').onclick=()=>recordForm(p);document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>recordForm(p,p.records.find(r=>r.id===b.dataset.edit)));document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>recordForm(p,p.records.find(r=>r.id===b.dataset.copy),true));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteRecord(p,b.dataset.delete))}

function form(title,html,save,label='儲存'){$('#modalTitle').textContent=title;$('#modalFields').innerHTML=html;$('#submitButton').textContent=label;if(!$('#modal').open)$('#modal').showModal();$('#modalForm').onsubmit=async e=>{e.preventDefault();$('#submitButton').disabled=true;try{const x=await save(new FormData(e.target));if(x?.error)return alert(x.error.message);$('#modal').close();await load()}catch(err){alert(`操作失敗：${err?.message||'未知錯誤'}`)}finally{$('#submitButton').disabled=false}}}
const opts=id=>categories.map(c=>`<option value="${c.id}" ${c.id===id?'selected':''}>${esc(c.name)}</option>`).join('');$('#cancel').onclick=()=>$('#modal').close();
$('#addPatient').onclick=()=>form('新增個案',`<label class="field">姓名<input name="name" required></label><label class="field">辨識代碼<input name="patient_code"></label><label class="field">分類<select name="category_id">${opts(categories.find(c=>c.is_system)?.id)}</select></label>`,f=>{const name=String(f.get('name')).trim();if(patients.some(p=>p.name===name)&&!confirm('已有同名個案，仍要建立嗎？'))return{error:{message:'已取消'}};return sb.from('patients').insert({name,patient_code:f.get('patient_code')||null,category_id:f.get('category_id')})});
function movePatient(p){form('移動分類',`<label class="field">分類<select name="category_id">${opts(p.category_id)}</select></label>`,f=>sb.from('patients').update({category_id:f.get('category_id'),updated_at:new Date().toISOString()}).eq('id',p.id),'移動')}
function editPatient(p){form('編輯個案',`<label class="field">姓名<input name="name" value="${esc(p.name)}" required></label><label class="field">辨識代碼<input name="patient_code" value="${esc(p.patient_code||'')}"></label><label class="field">主要分類<select name="category_id">${opts(p.category_id)}</select></label>`,f=>{const name=String(f.get('name')||'').trim();if(!name)return{error:{message:'請輸入姓名'}};if(name!==p.name&&patients.some(x=>x.id!==p.id&&x.name===name)&&!confirm('系統中已有同名個案，仍要儲存嗎？'))return{error:{message:'已取消'}};return sb.from('patients').update({name,patient_code:String(f.get('patient_code')||'').trim()||null,category_id:f.get('category_id'),updated_at:new Date().toISOString()}).eq('id',p.id)},'儲存變更')}
const sideName={left:'左',right:'右',bilateral:'雙側',none:'中央／不分側'};
function recordForm(p,r=null,copy=false){
  let chosenBodies=(r?.record_body_parts||[]).map(x=>({body_part_option_id:x.body_part_option_id,side:x.side,display_name:x.display_name,details:(x.record_body_part_details||[]).map(d=>({id:d.detail_option_id,display_name:d.display_name}))}));
  let chosenTreatments=(r?.record_treatments||[]).map(x=>({id:x.treatment_option_id,display_name:x.display_name}));
  const legacyBody=!chosenBodies.length?r?.body_part||'':'' ,legacyTreatment=!chosenTreatments.length?r?.treatment||'':'';
  const activeBodies=bodyOptions.filter(x=>x.is_active),activeTreatments=treatmentOptions.filter(x=>x.is_active);
  $('#modalTitle').textContent=copy?'複製成新紀錄':r?'編輯紀錄':'新增紀錄';
  $('#modalFields').innerHTML=`<label class="field">日期<input name="visit_date" type="date" value="${copy?new Date().toLocaleDateString('sv-SE'):r?.visit_date||new Date().toLocaleDateString('sv-SE')}" required></label>
  <section class="picker"><h3>1. 選擇側別</h3><div class="chipRow" id="sideButtons">${Object.entries(sideName).map(([k,v])=>`<button type="button" class="choice" data-side="${k}">${v}</button>`).join('')}</div>
  <h3>2. 選擇部位</h3>${[...new Set(activeBodies.map(x=>x.category))].map(g=>`<div class="optionGroup"><b>${esc(g)}</b><div class="chipRow">${activeBodies.filter(x=>x.category===g).map(x=>`<button type="button" class="choice" data-body="${x.id}">${esc(x.name)}</button>`).join('')}</div></div>`).join('')}
  <div id="detailPicker"></div><button type="button" class="primary" id="addBodyChoice">加入部位</button><div id="chosenBodies" class="chosenRow"></div>${legacyBody?`<p class="legacy">舊部位文字：${esc(legacyBody)}</p>`:''}</section>
  <section class="picker"><h3>3. 處理方式（可多選）</h3><div id="smartTreatments"></div><div id="chosenTreatments" class="chosenRow"></div>${legacyTreatment?`<p class="legacy">舊處理方式：${esc(legacyTreatment)}</p>`:''}${can('add_treatment')?'<button type="button" id="quickTreatment">＋ 新增處理方式</button>':''}</section>
  <label class="field">備註<textarea name="notes">${esc(copy?'':r?.notes||'')}</textarea></label>`;
  $('#submitButton').textContent='儲存';$('#modal').showModal();let side='none',bodyId=null,detailIds=[];
  const paintBodies=()=>{$('#chosenBodies').innerHTML=chosenBodies.map((x,i)=>`<button type="button" class="selectedChip" data-rmb="${i}">${esc(x.display_name)} ×</button>`).join('');document.querySelectorAll('[data-rmb]').forEach(b=>b.onclick=()=>{chosenBodies.splice(Number(b.dataset.rmb),1);paintBodies()})};
  const patientRecent=[...new Set((p.records||[]).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).flatMap(x=>(x.record_treatments||[]).map(y=>y.treatment_option_id)))].slice(0,5);
  const blocks=[['此個案最近使用',patientRecent],['我的常用',activeTreatments.filter(x=>x.is_pinned).map(x=>x.id)],['常用處理方式',[...activeTreatments].sort((a,b)=>b.usage_count-a.usage_count||new Date(b.last_used_at||0)-new Date(a.last_used_at||0)).map(x=>x.id)],['全部處理方式',activeTreatments.map(x=>x.id)]];
  const seen=new Set();$('#smartTreatments').innerHTML=blocks.map(([title,ids])=>{const unique=ids.filter(id=>!seen.has(id)&&seen.add(id));if(!unique.length)return'';return`<details class="optionBlock" open><summary>${title}</summary><div class="chipRow">${unique.map(id=>{const x=treatmentOptions.find(t=>t.id===id);return x?`<button type="button" class="choice" data-treatment="${id}">${esc(x.name)}</button>`:''}).join('')}</div></details>`}).join('');
  const paintTreatments=()=>{$('#chosenTreatments').innerHTML=chosenTreatments.map((x,i)=>`<button type="button" class="selectedChip" data-rmt="${i}">${esc(x.display_name)} ×</button>`).join('');document.querySelectorAll('[data-rmt]').forEach(b=>b.onclick=()=>{chosenTreatments.splice(Number(b.dataset.rmt),1);paintTreatments()});document.querySelectorAll('[data-treatment]').forEach(b=>b.classList.toggle('selected',chosenTreatments.some(x=>x.id===b.dataset.treatment)))};
  document.querySelectorAll('[data-side]').forEach(b=>b.onclick=()=>{side=b.dataset.side;document.querySelectorAll('[data-side]').forEach(x=>x.classList.toggle('selected',x===b))});
  document.querySelectorAll('[data-body]').forEach(b=>b.onclick=()=>{bodyId=b.dataset.body;detailIds=[];document.querySelectorAll('[data-body]').forEach(x=>x.classList.toggle('selected',x===b));const ds=bodyDetails.filter(x=>x.body_part_option_id===bodyId&&x.is_active);$('#detailPicker').innerHTML=ds.length?`<h3>3. 選擇部位細項（可多選）</h3><div class="chipRow">${ds.map(x=>`<button type="button" class="choice" data-detail="${x.id}">${esc(x.name)}</button>`).join('')}</div>`:'';document.querySelectorAll('[data-detail]').forEach(x=>x.onclick=()=>{x.classList.toggle('selected');detailIds=[...document.querySelectorAll('[data-detail].selected')].map(y=>y.dataset.detail)})});
  $('#addBodyChoice').onclick=()=>{const b=bodyOptions.find(x=>x.id===bodyId);if(!b)return alert('請先選擇部位');if(b.side_rule==='required'&&side==='none')return alert(`${b.name}必須選擇左、右或雙側`);const ds=detailIds.map(id=>bodyDetails.find(x=>x.id===id)).filter(Boolean),prefix=side==='none'?'':sideName[side],name=`${prefix}${b.name}${ds.length?'－'+ds.map(x=>x.name).join('／'):''}`;chosenBodies.push({body_part_option_id:b.id,side,display_name:name,details:ds.map(x=>({id:x.id,display_name:x.name}))});paintBodies()};
  document.querySelectorAll('[data-treatment]').forEach(b=>b.onclick=()=>{const x=treatmentOptions.find(t=>t.id===b.dataset.treatment),i=chosenTreatments.findIndex(y=>y.id===x.id);i>=0?chosenTreatments.splice(i,1):chosenTreatments.push({id:x.id,display_name:x.name});paintTreatments()});
  if($('#quickTreatment'))$('#quickTreatment').onclick=async()=>{const name=prompt('新增處理方式名稱');if(!name?.trim())return;const x=await sb.from('treatment_options').insert({name:name.trim(),sort_order:treatmentOptions.length}).select().single();if(x.error)return alert(x.error.message);await audit('新增處理方式','treatment_option',x.data.id,x.data.name);treatmentOptions.push(x.data);chosenTreatments.push({id:x.data.id,display_name:x.data.name});paintTreatments()};
  paintBodies();paintTreatments();
  $('#modalForm').onsubmit=async e=>{e.preventDefault();if(!chosenBodies.length)return alert(legacyBody?'這是舊格式紀錄，請先用按鍵重新選擇部位再儲存。':'請至少加入一個部位');if(!chosenTreatments.length)return alert(legacyTreatment?'這是舊格式紀錄，請先用按鍵重新選擇處理方式再儲存。':'請至少選擇一個處理方式');const f=new FormData(e.target),x=await sb.rpc('save_structured_record',{p_record_id:r&&!copy?r.id:null,p_patient_id:p.id,p_visit_date:f.get('visit_date'),p_notes:f.get('notes')||'',p_body_parts:chosenBodies,p_treatments:chosenTreatments});if(x.error)return alert(x.error.message);$('#modal').close();await load();openPatient(p.id)};
}
async function deleteRecord(p,id){if(!confirm('確定刪除此紀錄？'))return;const x=await sb.from('records').delete().eq('id',id);if(x.error)return alert(x.error.message);await load();openPatient(p.id)}
async function deletePatient(p){if(profile.role!=='super_admin')return alert('只有主管理員可以刪除整位個案');const name=prompt(`將刪除個案「${p.name}」及其全部 ${p.records.length} 筆紀錄。\n刪除後只能從備份還原。\n\n請輸入完整姓名確認：`);if(name===null)return;if(name.trim()!==p.name)return alert('姓名不一致，未執行刪除');const x=await sb.from('patients').delete().eq('id',p.id);if(x.error)return alert(x.error.message);await audit('刪除個案','patient',p.id,p.name);alert('個案已刪除');active='all';await load()}
$('#categoryManage').onclick=categoryManager;
$('#bodyPartManage').onclick=bodyPartManager;$('#treatmentManage').onclick=treatmentManager;
const allRecords=()=>patients.flatMap(p=>p.records||[]),bodyUsage=id=>allRecords().flatMap(r=>r.record_body_parts||[]).filter(x=>x.body_part_option_id===id).length,detailUsage=id=>allRecords().flatMap(r=>r.record_body_parts||[]).flatMap(x=>x.record_body_part_details||[]).filter(x=>x.detail_option_id===id).length;
async function reorder(table,list,id,dir){const i=list.findIndex(x=>x.id===id),j=i+dir;if(j<0||j>=list.length)return;await Promise.all([sb.from(table).update({sort_order:list[j].sort_order}).eq('id',list[i].id),sb.from(table).update({sort_order:list[i].sort_order}).eq('id',list[j].id)]);await load()}
function bodyPartManager(){const row=b=>`<div class="manageCard ${b.is_active?'':'inactive'}"><span><b>${esc(b.name)}</b><small>${esc(b.category)} · 已使用 ${bodyUsage(b.id)} 次 · ${b.is_active?'啟用':'停用'}</small></span><span><button type="button" data-bup="${b.id}">↑</button><button type="button" data-bdn="${b.id}">↓</button><button type="button" data-be="${b.id}">編輯</button><button type="button" data-bt="${b.id}">${b.is_active?'停用':'啟用'}</button><button type="button" data-bd="${b.id}">細項</button><button type="button" data-bx="${b.id}">刪除</button></span></div>`;form('部位設定',`<label class="field">新增部位<input name="name"></label><label class="field">分類<select name="category"><option>頭頸</option><option>上肢</option><option>軀幹</option><option>下肢</option><option>其他</option></select></label><label class="field">側別規則<select name="side_rule"><option value="required">必須選擇側別</option><option value="optional">側別可選</option><option value="none">預設不分側</option></select></label><div class="managerList">${bodyOptions.map(row).join('')}</div>`,f=>f.get('name')?sb.from('body_part_options').insert({name:String(f.get('name')).trim(),category:f.get('category'),side_rule:f.get('side_rule'),sort_order:bodyOptions.length*10}):({}),'新增部位');document.querySelectorAll('[data-be]').forEach(x=>x.onclick=async()=>{const b=bodyOptions.find(y=>y.id===x.dataset.be),name=prompt('部位名稱',b.name);if(name?.trim())await sb.from('body_part_options').update({name:name.trim()}).eq('id',b.id);$('#modal').close();await load();bodyPartManager()});document.querySelectorAll('[data-bt]').forEach(x=>x.onclick=async()=>{const b=bodyOptions.find(y=>y.id===x.dataset.bt);await sb.from('body_part_options').update({is_active:!b.is_active}).eq('id',b.id);$('#modal').close();await load();bodyPartManager()});document.querySelectorAll('[data-bx]').forEach(x=>x.onclick=async()=>{const n=bodyUsage(x.dataset.bx);if(n)return alert(`已被 ${n} 筆病歷使用，不能永久刪除，請改為停用。`);if(confirm('確定刪除此未使用部位？')){const z=await sb.from('body_part_options').delete().eq('id',x.dataset.bx);if(z.error)return alert('請先刪除所屬細項');$('#modal').close();await load();bodyPartManager()}});document.querySelectorAll('[data-bd]').forEach(x=>x.onclick=()=>detailManager(bodyOptions.find(y=>y.id===x.dataset.bd)));document.querySelectorAll('[data-bup],[data-bdn]').forEach(x=>x.onclick=async()=>{await reorder('body_part_options',bodyOptions,x.dataset.bup||x.dataset.bdn,x.dataset.bup?-1:1);$('#modal').close();bodyPartManager()})}
function detailManager(part){const list=bodyDetails.filter(x=>x.body_part_option_id===part.id),row=d=>`<div class="manageCard ${d.is_active?'':'inactive'}"><span><b>${esc(d.name)}</b><small>已使用 ${detailUsage(d.id)} 次</small></span><span><button type="button" data-du="${d.id}">↑</button><button type="button" data-dd="${d.id}">↓</button><button type="button" data-de="${d.id}">編輯</button><button type="button" data-dt="${d.id}">${d.is_active?'停用':'啟用'}</button><button type="button" data-dx="${d.id}">刪除</button></span></div>`;form(`${part.name}－細項設定`,`<label class="field">新增細項<input name="name"></label><div class="managerList">${list.map(row).join('')}</div>`,f=>f.get('name')?sb.from('body_part_detail_options').insert({body_part_option_id:part.id,name:String(f.get('name')).trim(),sort_order:list.length*10}):({}),'新增細項');document.querySelectorAll('[data-de]').forEach(x=>x.onclick=async()=>{const d=bodyDetails.find(y=>y.id===x.dataset.de),name=prompt('細項名稱',d.name);if(name?.trim())await sb.from('body_part_detail_options').update({name:name.trim()}).eq('id',d.id);$('#modal').close();await load();detailManager(part)});document.querySelectorAll('[data-dt]').forEach(x=>x.onclick=async()=>{const d=bodyDetails.find(y=>y.id===x.dataset.dt);await sb.from('body_part_detail_options').update({is_active:!d.is_active}).eq('id',d.id);$('#modal').close();await load();detailManager(part)});document.querySelectorAll('[data-dx]').forEach(x=>x.onclick=async()=>{const n=detailUsage(x.dataset.dx);if(n)return alert(`已使用 ${n} 次，只能停用。`);if(confirm('確定刪除此未使用細項？')){await sb.from('body_part_detail_options').delete().eq('id',x.dataset.dx);$('#modal').close();await load();detailManager(part)}});document.querySelectorAll('[data-du],[data-dd]').forEach(x=>x.onclick=async()=>{await reorder('body_part_detail_options',list,x.dataset.du||x.dataset.dd,x.dataset.du?-1:1);$('#modal').close();detailManager(part)})}
function treatmentManager(){
 const row=t=>`<div class="manageCard ${t.is_active?'':'inactive'}"><span><label><input type="checkbox" data-tselect="${t.id}"> <b>${t.is_pinned?'📌 ':''}${esc(t.name)}</b></label><small>使用 ${t.usage_count} 次 · 最後使用：${t.last_used_at?new Date(t.last_used_at).toLocaleString('zh-TW',{hour12:false}):'尚未使用'} · 建立：${new Date(t.created_at).toLocaleDateString('zh-TW')}</small></span><span>${can('pin_sort_treatment')?`<button type="button" data-tu="${t.id}">↑</button><button type="button" data-td="${t.id}">↓</button><button type="button" data-tp="${t.id}">${t.is_pinned?'取消釘選':'釘選'}</button>`:''}${can('edit_treatment')?`<button type="button" data-te="${t.id}">編輯</button>`:''}${can('toggle_treatment')?`<button type="button" data-tt="${t.id}">${t.is_active?'停用':'重新啟用'}</button>`:''}${can('delete_treatment')?`<button type="button" data-tx="${t.id}">永久刪除</button>`:''}</span></div>`;
 form('處理方式管理',`${can('add_treatment')?'<label class="field">新增處理方式<input name="name"></label><label><input name="is_pinned" type="checkbox"> 釘選</label>':''}<div class="recordActions"><button type="button" id="batchDisable">批次停用</button><button type="button" id="batchEnable">批次重新啟用</button><button type="button" id="batchUnpin">批次取消釘選</button><button type="button" id="batchDelete">批次刪除</button></div><div class="managerList"><h3>啟用中</h3>${treatmentOptions.filter(t=>t.is_active).map(row).join('')||'<p>目前沒有啟用中的處理方式</p>'}<h3>已停用</h3>${treatmentOptions.filter(t=>!t.is_active).map(row).join('')||'<p>目前沒有已停用的處理方式</p>'}</div>`,f=>f.get('name')?sb.from('treatment_options').insert({name:String(f.get('name')).trim(),is_pinned:f.get('is_pinned')==='on',sort_order:treatmentOptions.length*10}):({}),'新增處理方式');
 document.querySelectorAll('[data-te]').forEach(x=>x.onclick=async()=>{const t=treatmentOptions.find(y=>y.id===x.dataset.te),name=prompt('處理方式名稱',t.name);if(name?.trim()){const z=await sb.from('treatment_options').update({name:name.trim()}).eq('id',t.id);if(z.error)return alert(z.error.message);await audit('修改處理方式','treatment_option',t.id,name.trim())}$('#modal').close();await load();treatmentManager()});
 document.querySelectorAll('[data-tp],[data-tt]').forEach(x=>x.onclick=async()=>{const id=x.dataset.tp||x.dataset.tt,t=treatmentOptions.find(y=>y.id===id),turn=x.dataset.tp?{is_pinned:!t.is_pinned}:{is_active:!t.is_active};const z=await sb.from('treatment_options').update(turn).eq('id',id);if(z.error)return alert(z.error.message);await audit(x.dataset.tp?'變更處理方式釘選':t.is_active?'停用處理方式':'重新啟用處理方式','treatment_option',id,t.name);$('#modal').close();await load();treatmentManager()});
 document.querySelectorAll('[data-tx]').forEach(x=>x.onclick=async()=>{const t=treatmentOptions.find(y=>y.id===x.dataset.tx);if(t.usage_count){if(confirm(`此處理方式已被使用於 ${t.usage_count} 筆病歷，無法永久刪除。是否改為停用？`)){await sb.from('treatment_options').update({is_active:false}).eq('id',t.id);await audit('停用處理方式','treatment_option',t.id,t.name)}return}if(confirm('確定要永久刪除此處理方式嗎？此操作無法復原。')){await sb.from('treatment_options').delete().eq('id',t.id);await audit('刪除處理方式','treatment_option',t.id,t.name);$('#modal').close();await load();treatmentManager()}});
 document.querySelectorAll('[data-tu],[data-td]').forEach(x=>x.onclick=async()=>{await reorder('treatment_options',treatmentOptions,x.dataset.tu||x.dataset.td,x.dataset.tu?-1:1);$('#modal').close();treatmentManager()});
 const selected=()=>[...document.querySelectorAll('[data-tselect]:checked')].map(x=>treatmentOptions.find(t=>t.id===x.dataset.tselect)).filter(Boolean);
 const batch=async action=>{const list=selected();if(!list.length)return alert('請先勾選處理方式');let deleted=0,disabled=0,changed=0;for(const t of list){if(action==='delete'){if(t.usage_count){await sb.from('treatment_options').update({is_active:false}).eq('id',t.id);disabled++}else{await sb.from('treatment_options').delete().eq('id',t.id);deleted++}}else{await sb.from('treatment_options').update(action==='disable'?{is_active:false}:action==='enable'?{is_active:true}:{is_pinned:false}).eq('id',t.id);changed++}}await audit('批次管理處理方式','treatment_option',null,`刪除 ${deleted}、停用 ${disabled}、變更 ${changed}`);alert(`完成：永久刪除 ${deleted} 項、改為停用 ${disabled} 項、其他變更 ${changed} 項`);$('#modal').close();await load();treatmentManager()};
 $('#batchDisable').onclick=()=>batch('disable');$('#batchEnable').onclick=()=>batch('enable');$('#batchUnpin').onclick=()=>batch('unpin');$('#batchDelete').onclick=()=>confirm('批次刪除會永久刪除未使用項目；已使用項目會改為停用。確定繼續？')&&batch('delete')
}
function categoryManager(){form('分類管理',`<label class="field">新增分類<input name="name" placeholder="分類名稱"></label>${categories.map((c,i)=>`<div class="userrow"><span>📁 ${esc(c.name)}（${patients.filter(p=>p.category_id===c.id).length}）</span><span><button type="button" data-up="${c.id}" ${i===0?'disabled':''}>↑</button><button type="button" data-down="${c.id}" ${i===categories.length-1?'disabled':''}>↓</button><button type="button" data-rename="${c.id}">改名</button><button type="button" data-batch="${c.id}">移動</button>${c.is_system?'':`<button type="button" data-delcat="${c.id}">刪除</button>`}</span></div>`).join('')}`,f=>f.get('name')?sb.from('categories').insert({name:f.get('name'),sort_order:categories.length}):({}),'新增分類');document.querySelectorAll('[data-rename]').forEach(b=>b.onclick=async()=>{const c=categories.find(x=>x.id===b.dataset.rename),name=prompt('新的分類名稱',c.name);if(name){await sb.from('categories').update({name,updated_at:new Date().toISOString()}).eq('id',c.id);$('#modal').close();await load()}});document.querySelectorAll('[data-delcat]').forEach(b=>b.onclick=async()=>{if(patients.some(p=>p.category_id===b.dataset.delcat))return alert('分類內仍有個案，請先批次移動。');if(confirm('確定刪除此空分類？')){await sb.from('categories').delete().eq('id',b.dataset.delcat);$('#modal').close();await load()}});document.querySelectorAll('[data-up],[data-down]').forEach(b=>b.onclick=async()=>{const id=b.dataset.up||b.dataset.down,i=categories.findIndex(c=>c.id===id),j=b.dataset.up!==undefined?i-1:i+1;if(j<0||j>=categories.length)return;await Promise.all([sb.from('categories').update({sort_order:j}).eq('id',categories[i].id),sb.from('categories').update({sort_order:i}).eq('id',categories[j].id)]);$('#modal').close();await load();categoryManager()});document.querySelectorAll('[data-batch]').forEach(b=>b.onclick=async()=>{const source=b.dataset.batch,targets=categories.filter(c=>c.id!==source),target=prompt(`輸入目標分類名稱：\n${targets.map(c=>c.name).join('、')}`),cat=targets.find(c=>c.name===target);if(!cat)return target&&alert('找不到該分類');for(const p of patients.filter(p=>p.category_id===source))await sb.from('patients').update({category_id:cat.id,updated_at:new Date().toISOString()}).eq('id',p.id);$('#modal').close();await load()})}
const download=(name,text,type='text/plain')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click()};const csv=v=>`"${String(v??'').replaceAll('"','""')}"`;
$('#stats').onclick=()=>form('區間統計',`<label class="field">開始日期<input name="start" type="date" required></label><label class="field">結束日期<input name="end" type="date" value="${new Date().toLocaleDateString('sv-SE')}" required></label><label class="field">關鍵字<input name="q"></label><div id="statsResult"></div>`,f=>{const q=String(f.get('q')||'').toLowerCase(),rows=patients.flatMap(p=>(p.records||[]).filter(r=>r.visit_date>=f.get('start')&&r.visit_date<=f.get('end')&&(!q||`${p.name} ${r.body_part} ${r.treatment} ${r.notes}`.toLowerCase().includes(q))).map(r=>({...r,name:p.name})));$('#statsResult').innerHTML=`<h3>符合 ${rows.length} 筆，涉及 ${new Set(rows.map(r=>r.name)).size} 位個案</h3>`;return{error:{message:'統計已完成'}}},'開始統計');
const permissionLabels={manage_treatments:'管理處理方式',add_treatment:'新增處理方式',edit_treatment:'編輯處理方式',delete_treatment:'刪除未使用處理方式',toggle_treatment:'停用／重新啟用處理方式',pin_sort_treatment:'釘選及排序處理方式',manage_body_parts:'管理部位選項',manage_categories:'管理分類',export_data:'匯出資料'};
const permissionFields=(v={})=>`<fieldset class="permissionGrid"><legend>權限設定</legend>${Object.entries(permissionLabels).map(([k,n])=>`<label><input type="checkbox" name="${k}" ${v[k]?'checked':''}> ${n}</label>`).join('')}</fieldset>`;
const getPermissions=f=>Object.fromEntries(Object.keys(permissionLabels).map(k=>[k,f.get(k)==='on']));
async function adminCall(body){const{data,error}=await sb.functions.invoke('admin-users',{body});if(error)return{error:{message:error.context?await error.context.text():error.message}};if(data?.error)return{error:{message:data.error}};return{data}}
$('#users').onclick=accountManager;
async function accountManager(){const{data,error}=await sb.from('profiles').select('*').order('created_at');if(error)return alert(error.message);form('帳號與權限管理',`<button type="button" class="primary" id="addSubAdmin">＋ 新增子管理員</button><div class="managerList">${(data||[]).map(u=>`<div class="manageCard"><span><b>${esc(u.display_name||u.email)}</b><small>${esc(u.email)} · ${u.role==='super_admin'?'主管理員':'子管理員'} · ${u.active?'啟用':'停用'}<br>建立：${new Date(u.created_at).toLocaleString('zh-TW',{hour12:false})} · 最後登入：${u.last_login_at?new Date(u.last_login_at).toLocaleString('zh-TW',{hour12:false}):'尚未登入'}</small></span><span>${u.role==='super_admin'?'<b>主管理員</b>':`<button type="button" data-uedit="${u.id}">編輯／權限</button><button type="button" data-upass="${u.id}">重設密碼</button><button type="button" data-ulog="${u.id}">操作紀錄</button><button type="button" data-udel="${u.id}">刪除</button>`}</span></div>`).join('')}</div>`,()=>({}),'關閉');$('#addSubAdmin').onclick=addSubAdmin;document.querySelectorAll('[data-uedit]').forEach(x=>x.onclick=()=>editSubAdmin(data.find(u=>u.id===x.dataset.uedit)));document.querySelectorAll('[data-upass]').forEach(x=>x.onclick=()=>resetSubPassword(data.find(u=>u.id===x.dataset.upass)));document.querySelectorAll('[data-ulog]').forEach(x=>x.onclick=()=>showUserLogs(data.find(u=>u.id===x.dataset.ulog)));document.querySelectorAll('[data-udel]').forEach(x=>x.onclick=async()=>{if(!confirm('確定要永久刪除此從未使用的帳號嗎？'))return;const z=await adminCall({action:'delete',user_id:x.dataset.udel});if(z.error)return alert(z.error.message);$('#modal').close();accountManager()})}
function addSubAdmin(){form('新增子管理員',`<label class="field">顯示名稱<input name="display_name" required></label><label class="field">登入帳號<input name="email" type="email" required></label><label class="field">初始密碼<input name="password" type="password" minlength="8" required></label><label class="field">確認密碼<input name="confirm" type="password" minlength="8" required></label><label><input type="checkbox" name="active" checked> 帳號啟用</label><label><input type="checkbox" name="must_change_password" checked> 下次登入必須修改密碼</label>${permissionFields()}`,f=>{if(f.get('password')!==f.get('confirm'))return{error:{message:'兩次密碼不一致'}};return adminCall({action:'create',display_name:f.get('display_name'),email:f.get('email'),password:f.get('password'),active:f.get('active')==='on',must_change_password:f.get('must_change_password')==='on',permissions:getPermissions(f)})},'建立子管理員')}
function editSubAdmin(u){form('編輯子管理員',`<label class="field">顯示名稱<input name="display_name" value="${esc(u.display_name||'')}" required></label><label><input type="checkbox" name="active" ${u.active?'checked':''}> 帳號啟用</label>${permissionFields(u.permissions||{})}`,f=>adminCall({action:'update',user_id:u.id,display_name:f.get('display_name'),active:f.get('active')==='on',permissions:getPermissions(f)}),'儲存變更')}
function resetSubPassword(u){form('重設子管理員密碼',`<p>${esc(u.email)}</p><label class="field">新密碼<input name="password" type="password" minlength="8" required></label><label class="field">確認密碼<input name="confirm" type="password" minlength="8" required></label><label><input type="checkbox" name="must_change_password" checked> 下次登入必須修改密碼</label>`,f=>f.get('password')!==f.get('confirm')?{error:{message:'兩次密碼不一致'}}:adminCall({action:'reset_password',user_id:u.id,password:f.get('password'),must_change_password:f.get('must_change_password')==='on'}),'重設密碼')}
async function showUserLogs(u){const{data}=await sb.from('audit_logs').select('*').eq('user_id',u.id).order('created_at',{ascending:false}).limit(100);form(`${u.display_name||u.email}－操作紀錄`,(data||[]).map(x=>`<div class="manageCard"><span><b>${esc(x.action)}</b><small>${new Date(x.created_at).toLocaleString('zh-TW',{hour12:false})} · ${esc(x.entity_type||'系統')} ${esc(x.entity_id||'')}<br>${esc(x.description||'')}</small></span></div>`).join('')||'<p>尚無操作紀錄</p>',()=>({}),'關閉')}
$('#importJson').onclick=()=>$('#jsonFile').click();$('#jsonFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;let doc;try{doc=JSON.parse(await file.text())}catch{return alert('JSON 檔案格式錯誤')}if(doc.schema_version!==2||!Array.isArray(doc.categories)||!Array.isArray(doc.patients)||!Array.isArray(doc.records))return alert('這不是 AT Case Library v2 完整備份');if(!confirm(`即將匯入：${doc.categories.length} 個分類、${doc.patients.length} 位個案、${doc.records.length} 筆紀錄。\n目前資料會先自動備份，再由匯入資料取代。確定繼續？`))return;const x=await sb.rpc('import_case_library_json',{p_payload:doc});if(x.error)return alert(x.error.message);alert('JSON 匯入完成');location.reload()};
$('#backup').onclick=async()=>{const{data:backs}=profile.role==='super_admin'?await sb.from('backup_snapshots').select('id,reason,created_at').order('created_at',{ascending:false}):{data:[]};form('備份與資料管理',`<div class="recordActions"><button type="button" id="jsonOut">JSON</button><button type="button" id="csvOut">CSV</button><button type="button" id="xlsOut">Excel</button><button type="button" id="sqlOut">SQL 封存</button></div>${profile.role==='super_admin'?`<button type="button" id="backupNow">立即建立雲端備份</button><h3>最近備份</h3>${(backs||[]).slice(0,50).map(b=>`<div class="userrow"><span>${new Date(b.created_at).toLocaleString('zh-TW')}<small>${esc(b.reason)}</small></span><button type="button" data-restore="${b.id}">還原</button></div>`).join('')}`:''}`,()=>({}),'關閉');const rows=patients.flatMap(p=>(p.records||[]).map(r=>({name:p.name,category:categories.find(c=>c.id===p.category_id)?.name,date:r.visit_date,body:r.body_part,treatment:r.treatment,notes:r.notes}))),doc={schema_version:2,exported_at:new Date().toISOString(),categories,patients:patients.map(({records,...p})=>p),records:patients.flatMap(p=>p.records||[])};$('#jsonOut').onclick=()=>download(`at-case-${Date.now()}.json`,JSON.stringify(doc,null,2),'application/json');$('#csvOut').onclick=()=>download(`at-case-${Date.now()}.csv`,['姓名,分類,日期,部位,處理方式,備註',...rows.map(r=>[r.name,r.category,r.date,r.body,r.treatment,r.notes].map(csv).join(','))].join('\n'),'text/csv;charset=utf-8');$('#xlsOut').onclick=()=>download(`at-case-${Date.now()}.xls`,`<table><tr><th>姓名</th><th>分類</th><th>日期</th><th>部位</th><th>處理方式</th><th>備註</th></tr>${rows.map(r=>`<tr>${Object.values(r).map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</table>`,'application/vnd.ms-excel');$('#sqlOut').onclick=()=>download(`at-case-${Date.now()}.sql`,`-- AT Case Library offline archive\n-- JSON payload follows\n${JSON.stringify(doc)}`);if($('#backupNow'))$('#backupNow').onclick=async()=>{await sb.rpc('create_case_library_backup',{p_reason:'manual'});alert('備份完成')};document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=async()=>{if(confirm('還原會覆蓋目前資料；系統會先備份當下狀態。確定繼續？')){const x=await sb.rpc('restore_case_library_backup',{p_backup_id:Number(b.dataset.restore)});if(x.error)return alert(x.error.message);location.reload()}})};
$('#globalSearch').oninput=renderFolders;$('#sort').onchange=renderFolders;document.querySelector('[data-view="all"]').onclick=()=>{active='all';renderSide();renderFolders()};$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');boot();
