import {readFile, writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';

const root=fileURLToPath(new URL('../',import.meta.url));
const sources=[];

// Flatten only local, unconditional imports; preserve every rule and its order.
async function flatten(name,parents=[]){
  if(parents.includes(name))throw new Error(`Circular CSS import: ${name}`);
  const filename=path.resolve(root,name);
  if(path.dirname(filename)!==path.resolve(root))throw new Error(`Unexpected CSS path: ${name}`);
  const source=await readFile(filename,'utf8');
  const imports=[...source.matchAll(/@import\s+url\(['"]\.\/([^'"]+)['"]\);/g)];
  let result='',offset=0;
  for(const match of imports){
    result+=source.slice(offset,match.index)+await flatten(match[1],[...parents,name]);
    offset=match.index+match[0].length;
  }
  result+=source.slice(offset);
  if(/@import\b|@charset\b/.test(result))throw new Error(`Unsupported CSS directive: ${name}`);
  sources.push(name);
  return result;
}

const css=await flatten('v13-style.css');
const output=`/* Generated by node scripts/build.mjs. Edit the v*-style.css source files. */\n${css}`;
const target=path.join(root,'app-style.css');
if(process.argv.includes('--check')){
  if(await readFile(target,'utf8')!==output)throw new Error('app-style.css is stale; run node scripts/build.mjs');
}else{
  await writeFile(target,output);
}
console.log(`Styles verified: ${sources.length} source files → 1 stylesheet (${Buffer.byteLength(output)} bytes)`);
